<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>try catch and finally</h1>
<script>
     class AppError extends Error{
             constructor(msg){
                super(msg)
                 this.msg = msg
             }
         }

        function f1(){
            const number = Math.floor(Math.random()*10+1)
            if(number > 4){
                // affaffa()
                // throw new Error('error')
                throw new AppError('Viswanath is a very silent guy')
            }
            console.log('hello hello');
            
        }
        try{
            f1()
        }
        catch(err){
            console.log('error occurd' , err);
            
        }
        finally{
            console.log('Finally executed');
            
        }
    </script>
    
</body>
</html>